version: 0.2

env:
  git-credential-helper: yes
  variables:
     templates: |
        sparc-db.yaml       
        master-stack.yaml
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - echo "validating templates"
      - ls -lt
      - cat README.md
      - FILES=$(echo $templates)
      - for cfnfiles in $FILES; do aws cloudformation validate-template --template-body file://$cfnfiles; done
  build:
    commands:
       - FILES=$(echo $templates)
       - for cfnfiles in $FILES; do aws s3 cp $cfnfiles s3://spc-template-store; done
artifacts:
  files:
    - application.zip
