version: 0.2

env:
  git-credential-helper: yes
  environment_variables:
  plaintext:
    templates: |
      sparc-db.yaml      
      master-stack.yaml
    environment_config: |
      "env-dev. json"
      "env-qa.json"
      "env-prod.json"
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - ls -lt
      - cat README.md
      - |
        for cfsfiles in $templates
        do
           aws cloudformation validate-template --template-body file://$templates
        done
  build:
    commands:
      - |
        for cfnfiles in $templates
        do
           aws s3 cp $cfsfiles s3://spc-template-store
        done
      - |
        for config in $environment_config
        do
           aws s3 cp $config s3://spc-template-strore
        done
artifacts:
  files:
    - application.zip
