version: 0.2

env:
  git-credential-helper: yes
  environment_variables:
  plaintext:
    templates: |
      sparc-db.yaml      
      master-stack.yaml
phases:
  install:
    runtime-versions:
      python: 3.9
  pre_build:
    commands:
      - ls -lt
      - cat README.md
      - |
        for files in $templates; do
           echo $files
           aws cloudformation validate-template --template-body file://$templates
        done
  build:
    commands:
      - |
        for cfnfiles in $templates; do
           echo "cfnfiles $cfnfiles"
           aws s3 cp $cfsfiles s3://spc-template-store
        done
artifacts:
  files:
    - application.zip
